language: cpp

sudo: false

cache:
  directories:
    - $HOME/itpp

compiler:
  - gcc

addons:
  apt:
    packages:
      - libsndfile1-dev
      - libfftw3-dev
      - liblapack3gf
      - libblas3gf

install:
  - bash travis_deps.sh

before_script:
  - export CMAKE_PREFIX_PATH=$HOME/mbelib:$HOME/itpp
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
